workspace = {members = ["src/tessoku-book"],exclude = []}
[package]
name = "kyopro"
version = "0.1.0"
authors = ["sayoi341 <me@sayoi341.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
